version: '3.8'

services:
  mcp:
    image: geekflarehq/geekflare-api-mcp:latest
    restart: always
    environment:
      MCP_TRANSPORT: http
      API_BASE_URL: ${API_BASE_URL:-https://api.geekflare.com}
      PORT: ${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
